import { SERVER_MESSAGES } from "./server-messages";
import { createContext, useContext, useEffect, useState, ReactNode } from "react";

export type Language = "en" | "vi" | "zh";

/** The languages a player can pick, in menu order (Chinese is Traditional, for Taiwan and Hong Kong) */
export const LANGUAGES: { id: Language; label: string; short: string; html: string; locale: string }[] = [
  { id: "vi", label: "Tiếng Việt", short: "VI", html: "vi", locale: "vi-VN" },
  { id: "en", label: "English", short: "EN", html: "en", locale: "en-US" },
  { id: "zh", label: "繁體中文", short: "中", html: "zh-Hant", locale: "zh-TW" },
];

/** Text that comes with its own translations (game data, menus) */
export type LocalText = { vi: string; en: string; zh?: string };

const en = {
  installTitle: "Get the VnSlot 888 app",
  installDesc: "Free. Opens full-screen from your home screen, like any app.",
  installBannerSub: "Play from your home screen, full-screen",
  installShort: "Install app",
  installNow: "Install now",
  installDone: "Installed. Open VnSlot 888 from your home screen.",
  installIos1: "In Safari, tap the Share button",
  installIos2: "Scroll down and tap",
  installIosAdd: "Add to Home Screen",
  installIos3: "Tap",
  installIosConfirm: "Add",
  installAndroid1: "In Chrome, tap the menu",
  installAndroid2: "Tap “Install app” or “Add to Home screen”",
  notNow: "Not now",
  privacy: "Privacy",
  deleteAccount: "Delete account",
  deleteAccountDesc: "Permanently deletes your account, coins, statistics and achievements. This can't be undone.",
  deleteConfirm: "I understand my account and coins will be gone for good",
  accountDeleted: "Your account has been deleted",
  gameSlot: "Slot",
  gameBauCua: "Bầu Cua",
  gameRoulette: "Roulette",
  gameBlackjack: "Blackjack",
  gamePool: "Pool",
  gameLoto: "Lô Tô",
  gameTienLen: "Tiến Lên",
  gameBanca: "Bắn Cá",
  gameCardTables: "Bàn Bài",
  bcTitle: "Bầu Cua Tôm Cá",
  bcSubtitle: "The Tết dice game",
  bcNames: { bau: "Gourd", cua: "Crab", tom: "Shrimp", ca: "Fish", ga: "Rooster", nai: "Deer" },
  bcRules: "Bet on any of the six pictures, then roll three dice. A picture on one die pays 1 to 1, on two dice 2 to 1, on all three 3 to 1. Return to player: 92.13%, exactly as the traditional game.",
  rlTitle: "Roulette",
  rlSubtitle: "European single zero",
  rlRules: "Bet on a number (pays 35 to 1), a dozen or column (2 to 1), or red/black, odd/even, 1-18/19-36 (1 to 1). Zero loses every outside bet. Return to player: 97.30%.",
  pickChip: "Pick a chip, then tap where to bet",
  roll: "ROLL",
  spinWheel: "SPIN",
  clearBets: "Clear",
  undo: "Undo",
  onTable: "On the table",
  tableWin: "You won",
  tableLose: "No luck this time",
  placeBetFirst: "Place a bet first",
  lastNumbers: "Last numbers",
  red: "Red", black: "Black", odd: "Odd", even: "Even",
  rules: "Rules",
  login: "Enter Realm",
  register: "Join Dynasty",
  username: "Username",
  password: "Password",
  spin: "SPIN",
  bet: "Bet",
  balance: "Treasury",
  logout: "Log out",
  leaderboard: "Hall of Legends",
  loading: "Summoning luck...",
  streak: "Win Streak",
  topUp: "Free Coins",
  autoSpin: "Auto",
  totalWins: "Total Wins",
  maxWin: "Biggest Win",
  gamesPlayed: "Games Played",
  deposit: "Free Coins",
  about: "About",
  terms: "Terms",
  support: "Support",
  beginQuest: "Play Free",
  subtitle: "888 Dragon Fortune",
  description: "A free-to-play Vietnamese-style slot. Spin the reels, line up the",
  descriptionDragon: "Dragon",
  descriptionEnd: ", then try Bầu Cua Tôm Cá and roulette, all on one coin balance. Play money only — no real money in, no real money out.",
  maxWinStat: "TOP PAYOUT",
  freeSpins: "FREE SPINS",
  dailyCoins: "DAILY COINS",
  feature1: "10 PAYLINES",
  feature1Desc: "5 reels, 3 rows: 3, 4 or 5 in a row from the left. Every win pays at least your bet back",
  feature2: "WILDS & LÌ XÌ",
  feature2Desc: "🔮 Dragon Pearl wilds complete lines. 🧧 3+ red envelopes pay anywhere and you choose your free spins",
  feature3: "RỒNG LẶP & HŨ RỒNG",
  feature3Desc: "3 🔮 anywhere wake the dragon: pearls stick and the rest re-spins at ×2 to ×12. Middle-row 🔮🔮🔮 bursts the shared jackpot",
  achievements: "Achievements",
  topPlayers: "Top Players",
  won: "won",
  noPlayersYet: "No players yet",
  noWinsYet: "No big wins yet — be the first!",
  games: "Games",
  wins: "Wins",
  profile: "Profile",
  insufficientBalance: "Not enough coins",
  insufficientBalanceDesc: "Lower your bet or grab your free daily coins.",
  niceWin: "NICE WIN!",
  bigWin: "BIG WIN!",
  hugeWin: "MEGA WIN!",
  megaWin: "DRAGON FORTUNE!",
  youWon: "You won",
  smallWin: "Small win",
  scatterWin: "LUCKY ENVELOPES!",
  freeSpinsMode: "FREE SPINS",
  wild: "WILD",
  scatter: "SCATTER",
  anywhere: "anywhere",
  paytableWild: "🔮 Dragon Pearl is WILD: it stands in for any symbol on a line, and a run of pearls pays by itself (the 🔮 row above).",
  paytableScatter: "🧧 Red envelopes pay anywhere, no line needed, and win free spins. You choose how to take them (Chọn Lì Xì): more spins, or fewer spins with every win multiplied. Every choice is worth the same on average:",
  noWin: "No win this time",
  freeSpinsLeft: "free spins",
  freeSpinsWon: "free spins won!",
  oracle: "Oracle",
  oracleBlessed: "Draw a fortune stick: its grade blesses your next spin (×1.5 to ×5)",
  oracleCooldown: "The Oracle is resting. Back at",
  blessedBadge: "BLESSED NEXT SPIN",
  paytable: "Paytable",
  paytableIntro: "3, 4 or 5 matching symbols in a row from the leftmost reel, on any of the 10 lines, pay the multiple below times your bet. All lines add up.",
  paytableFree: "Free spins are played at the bet that won them. More envelopes during free spins add spins at the same multiplier.",
  rtpNote: "Return to player: 95.9% from the game with the best HOLD choices (87.7% if you never hold; measured over 40 million spins) plus the 1% that feeds the jackpot. The Xóc Đĩa double-up pays exactly fair odds, so it never changes that. Every symbol is drawn independently by a cryptographic RNG.",
  repeater: "RỒNG LẶP",
  repeaterGo: "RỒNG LẶP",
  paytableRepeater: "🐉 Rồng Lặp: 2 🔮 anywhere wake the dragon for two free re-spins; 3 or more wake the full ladder. The pearls stick, winning symbols lock and everything else re-spins free. Each new line, or a line that grows longer, pays with the next multiplier, and it keeps going while you keep winning:",
  jackpotName: "HŨ RỒNG",
  jackpotWin: "NỔ HŨ!",
  paytableJackpot: "🏺 Hũ Rồng jackpot: 1% of every bet goes into a shared pot. Three 🔮 on the middle row of reels 1-3 (on the spin or any repeat) win it: your share grows with your bet: 1K wins 0.1% of the pot, 100K wins 10%, 1M wins the whole pot. The pot never drops below 100M, so every bet wins at least 100× itself.",
  jackpotLast: "Last won by",
  jackpotYourBet: "Your bet",
  error: "Error",
  copyright: "© VnSlot 888 · Free-to-play entertainment · 18+",
  live: "BIG WINS",
  firstName: "First Name",
  lastName: "Last Name",
  saveChanges: "Save Changes",
  memberSince: "Member Since",
  editProfile: "Edit Profile",
  profileUpdated: "Profile updated",
  changePassword: "Change Password",
  currentPassword: "Current password",
  newPassword: "New password",
  passwordChanged: "Password changed",
  playMoneyNote: "Coins are play money. They can't be bought for cash or exchanged for money or prizes.",
  sound: "Sound",
  max: "Best",
  onFire: "On Fire!",
  unstoppable: "Unstoppable!",
  dragonMode: "Dragon Mode!",
  rank: "Rank",
  legendsTagline: "Legends of the Dragon",
  emptyLeaderboard: "The arena is silent. Be the first to claim your throne!",
};

export type Translations = typeof en;

const vi: Translations = {
  installTitle: "Tải ứng dụng VnSlot 888",
  installDesc: "Miễn phí. Mở toàn màn hình từ màn hình chính, như mọi ứng dụng.",
  installBannerSub: "Chơi ngay từ màn hình chính, toàn màn hình",
  installShort: "Tải ứng dụng",
  installNow: "Cài đặt ngay",
  installDone: "Đã cài đặt. Mở VnSlot 888 từ màn hình chính.",
  installIos1: "Trong Safari, chạm nút Chia sẻ",
  installIos2: "Kéo xuống và chạm",
  installIosAdd: "Thêm vào MH chính",
  installIos3: "Chạm",
  installIosConfirm: "Thêm",
  installAndroid1: "Trong Chrome, chạm vào menu",
  installAndroid2: "Chạm “Cài đặt ứng dụng” hoặc “Thêm vào màn hình chính”",
  notNow: "Để sau",
  privacy: "Quyền riêng tư",
  deleteAccount: "Xoá tài khoản",
  deleteAccountDesc: "Xoá vĩnh viễn tài khoản, xu, thống kê và thành tích của bạn. Không thể hoàn tác.",
  deleteConfirm: "Tôi hiểu tài khoản và xu sẽ bị xoá vĩnh viễn",
  accountDeleted: "Tài khoản của bạn đã được xoá",
  gameSlot: "Slot",
  gameBauCua: "Bầu Cua",
  gameRoulette: "Roulette",
  gameBlackjack: "Xì Dách",
  gamePool: "Bi-a",
  gameLoto: "Lô Tô",
  gameTienLen: "Tiến Lên",
  gameBanca: "Bắn Cá",
  gameCardTables: "Bàn Bài",
  bcTitle: "Bầu Cua Tôm Cá",
  bcSubtitle: "Trò chơi ngày Tết",
  bcNames: { bau: "Bầu", cua: "Cua", tom: "Tôm", ca: "Cá", ga: "Gà", nai: "Nai" },
  bcRules: "Đặt cược vào một trong sáu linh vật rồi lắc ba xúc xắc. Ra một mặt trả 1 ăn 1, hai mặt 1 ăn 2, ba mặt 1 ăn 3. Tỷ lệ hoàn trả: 92,13%, đúng như trò chơi truyền thống.",
  rlTitle: "Roulette",
  rlSubtitle: "Châu Âu, một số 0",
  rlRules: "Cược một số (1 ăn 35), một tá hoặc một cột (1 ăn 2), hoặc đỏ/đen, lẻ/chẵn, 1-18/19-36 (1 ăn 1). Số 0 thua mọi cược ngoài. Tỷ lệ hoàn trả: 97,30%.",
  pickChip: "Chọn phỉnh rồi chạm vào ô để cược",
  roll: "LẮC",
  spinWheel: "QUAY",
  clearBets: "Xoá",
  undo: "Hoàn tác",
  onTable: "Tiền cược",
  tableWin: "Bạn thắng",
  tableLose: "Chưa may mắn",
  placeBetFirst: "Hãy đặt cược trước",
  lastNumbers: "Kết quả gần đây",
  red: "Đỏ", black: "Đen", odd: "Lẻ", even: "Chẵn",
  rules: "Luật chơi",
  login: "Vào Cung",
  register: "Gia Nhập",
  username: "Tên đăng nhập",
  password: "Mật khẩu",
  spin: "QUAY",
  bet: "Mức Cược",
  balance: "Ngân Khố",
  logout: "Đăng xuất",
  leaderboard: "Bảng Phong Thần",
  loading: "Đang triệu hồi...",
  streak: "Chuỗi Thắng",
  topUp: "Xu Miễn Phí",
  autoSpin: "Tự động",
  totalWins: "Tổng Thắng",
  maxWin: "Thắng Lớn Nhất",
  gamesPlayed: "Lượt Chơi",
  deposit: "Xu Miễn Phí",
  about: "Giới Thiệu",
  terms: "Điều Khoản",
  support: "Hỗ Trợ",
  beginQuest: "Chơi Miễn Phí",
  subtitle: "888 Long Phát Tài",
  description: "Trò chơi slot phong cách Việt, hoàn toàn miễn phí. Quay, xếp hàng",
  descriptionDragon: "Rồng",
  descriptionEnd: ", rồi thử Bầu Cua Tôm Cá và Roulette, chung một ví xu. Chỉ dùng xu ảo — không nạp tiền thật, không rút tiền thật.",
  maxWinStat: "THƯỞNG CAO NHẤT",
  freeSpins: "LƯỢT QUAY MIỄN PHÍ",
  dailyCoins: "XU MỖI NGÀY",
  feature1: "10 HÀNG THƯỞNG",
  feature1Desc: "5 cuộn, 3 hàng: 3, 4 hoặc 5 biểu tượng liền nhau từ trái. Mọi lần thắng đều ít nhất hoàn lại tiền cược",
  feature2: "WILD & LÌ XÌ",
  feature2Desc: "🔮 Ngọc Rồng thay thế mọi biểu tượng. 🧧 3 lì xì trở lên trả thưởng ở bất kỳ ô nào và bạn tự chọn lượt quay miễn phí",
  feature3: "RỒNG LẶP & HŨ RỒNG",
  feature3Desc: "3 🔮 ở bất kỳ đâu đánh thức Rồng: ngọc được giữ lại, phần còn lại quay tiếp với hệ số ×2 đến ×12. 🔮🔮🔮 hàng giữa làm nổ hũ chung",
  achievements: "Thành Tựu",
  topPlayers: "Người Chơi Hàng Đầu",
  won: "thắng",
  noPlayersYet: "Chưa có người chơi",
  noWinsYet: "Chưa có thắng lớn — hãy là người đầu tiên!",
  games: "Ván",
  wins: "Thắng",
  profile: "Hồ Sơ",
  insufficientBalance: "Không đủ xu",
  insufficientBalanceDesc: "Giảm mức cược hoặc nhận xu miễn phí hằng ngày.",
  niceWin: "THẮNG ĐẸP!",
  bigWin: "THẮNG LỚN!",
  hugeWin: "THẮNG CỰC LỚN!",
  megaWin: "LONG PHÁT TÀI!",
  youWon: "Bạn thắng",
  smallWin: "Thắng nhỏ",
  scatterWin: "LÌ XÌ MAY MẮN!",
  freeSpinsMode: "QUAY MIỄN PHÍ",
  wild: "WILD",
  scatter: "SCATTER",
  anywhere: "bất kỳ đâu",
  paytableWild: "🔮 Ngọc Rồng là WILD: thay thế mọi biểu tượng trên hàng thưởng, và một chuỗi ngọc cũng tự trả thưởng (dòng 🔮 ở trên).",
  paytableScatter: "🧧 Lì xì trả thưởng ở bất kỳ ô nào, không cần xếp hàng, và tặng lượt quay miễn phí. Bạn tự chọn cách nhận (Chọn Lì Xì): nhiều lượt, hoặc ít lượt hơn nhưng mọi khoản thắng được nhân lên. Mọi lựa chọn có giá trị trung bình như nhau:",
  noWin: "Chưa trúng lần này",
  freeSpinsLeft: "lượt miễn phí",
  freeSpinsWon: "lượt quay miễn phí!",
  oracle: "Thần Rồng",
  oracleBlessed: "Xin một quẻ xăm: quẻ càng tốt, lượt quay tới càng được nhân nhiều (×1,5 đến ×5)",
  oracleCooldown: "Thần Rồng đang nghỉ. Quay lại lúc",
  blessedBadge: "ĐƯỢC BAN PHƯỚC",
  paytable: "Bảng Thưởng",
  paytableIntro: "3, 4 hoặc 5 biểu tượng giống nhau liền nhau từ cuộn đầu tiên bên trái, trên bất kỳ hàng nào trong 10 hàng, trả bội số dưới đây nhân với mức cược. Các hàng được cộng dồn.",
  paytableFree: "Lượt quay miễn phí dùng mức cược đã thắng chúng. Lì xì trong lượt miễn phí cho thêm lượt với cùng hệ số nhân.",
  rtpNote: "Tỷ lệ hoàn trả: 95,9% từ trò chơi khi giữ cuộn đúng cách (87,7% nếu không bao giờ giữ; đo trên 40 triệu lượt quay) cộng 1% góp vào hũ. Xóc Đĩa nhân đôi trả đúng tỷ lệ công bằng nên không làm thay đổi con số này. Mỗi biểu tượng được chọn độc lập bằng bộ sinh số ngẫu nhiên mật mã.",
  repeater: "RỒNG LẶP",
  repeaterGo: "RỒNG LẶP",
  paytableRepeater: "🐉 Rồng Lặp: 2 🔮 ở bất kỳ đâu đánh thức Rồng cho 2 lượt quay lại miễn phí; 3 🔮 trở lên mở cả thang nhân. Ngọc Rồng được giữ lại, biểu tượng thắng được khóa và phần còn lại quay miễn phí. Mỗi hàng thắng mới, hoặc hàng dài thêm, được nhân hệ số tiếp theo, và tiếp tục chừng nào bạn còn thắng:",
  jackpotName: "HŨ RỒNG",
  jackpotWin: "NỔ HŨ!",
  paytableJackpot: "🏺 Hũ Rồng: 1% mỗi lượt cược được góp vào hũ chung. Ba 🔮 ở hàng giữa của cuộn 1-3 (lượt quay hoặc lượt lặp) sẽ nổ hũ: phần thưởng tăng theo mức cược: 1K nhận 0,1% hũ, 100K nhận 10%, 1M nhận toàn bộ hũ. Hũ không bao giờ dưới 100 triệu, nên mọi mức cược đều thắng ít nhất 100 lần.",
  jackpotLast: "Lần nổ gần nhất",
  jackpotYourBet: "Cược",
  error: "Lỗi",
  copyright: "© VnSlot 888 · Giải trí miễn phí · 18+",
  live: "THẮNG LỚN",
  firstName: "Tên",
  lastName: "Họ",
  saveChanges: "Lưu Thay Đổi",
  memberSince: "Thành Viên Từ",
  editProfile: "Chỉnh Sửa Hồ Sơ",
  profileUpdated: "Đã cập nhật hồ sơ",
  changePassword: "Đổi Mật Khẩu",
  currentPassword: "Mật khẩu hiện tại",
  newPassword: "Mật khẩu mới",
  passwordChanged: "Đã đổi mật khẩu",
  playMoneyNote: "Xu chỉ dùng để chơi. Không thể mua bằng tiền thật hay đổi ra tiền hoặc giải thưởng.",
  sound: "Âm thanh",
  max: "Cao nhất",
  onFire: "Đang Bốc Lửa!",
  unstoppable: "Không Thể Cản!",
  dragonMode: "Chế Độ Rồng!",
  rank: "Hạng",
  legendsTagline: "Huyền Thoại Của Rồng",
  emptyLeaderboard: "Đấu trường còn trống. Hãy là người đầu tiên lên ngôi!",
};

const zh: Translations = {
  installTitle: "下載 VnSlot 888 App",
  installDesc: "免費。從主畫面以全螢幕開啟，就像一般 App。",
  installBannerSub: "從主畫面全螢幕暢玩",
  installShort: "安裝 App",
  installNow: "立即安裝",
  installDone: "已安裝。請從主畫面開啟 VnSlot 888。",
  installIos1: "在 Safari 中，點選「分享」按鈕",
  installIos2: "往下捲動並點選",
  installIosAdd: "加入主畫面",
  installIos3: "點選",
  installIosConfirm: "新增",
  installAndroid1: "在 Chrome 中，點選選單",
  installAndroid2: "點選「安裝應用程式」或「加到主畫面」",
  notNow: "以後再說",
  privacy: "隱私權",
  deleteAccount: "刪除帳號",
  deleteAccountDesc: "永久刪除你的帳號、金幣、統計資料和成就。此操作無法復原。",
  deleteConfirm: "我了解我的帳號和金幣將永久消失",
  accountDeleted: "你的帳號已刪除",
  gameSlot: "老虎機",
  gameBauCua: "魚蝦蟹",
  gameRoulette: "輪盤",
  gameBlackjack: "21點",
  gamePool: "撞球",
  gameLoto: "賓果",
  gameTienLen: "大老二",
  gameBanca: "捕魚",
  gameCardTables: "牌桌",
  bcTitle: "魚蝦蟹 (Bầu Cua)",
  bcSubtitle: "過年骰子遊戲",
  bcNames: { bau: "葫蘆", cua: "蟹", tom: "蝦", ca: "魚", ga: "雞", nai: "鹿" },
  bcRules: "押注六個圖案中的任一個，然後擲三顆骰子。圖案出現在一顆骰子上賠 1 比 1，兩顆賠 2 比 1，三顆全中賠 3 比 1。返還率：92.13%，與傳統玩法完全相同。",
  rlTitle: "輪盤",
  rlSubtitle: "歐式單零",
  rlRules: "押單一號碼（賠 35 比 1）、一打或一列（賠 2 比 1），或紅/黑、單/雙、1-18/19-36（賠 1 比 1）。開出 0 時所有外圍押注皆輸。返還率：97.30%。",
  pickChip: "選擇籌碼，再點選要下注的位置",
  roll: "擲骰",
  spinWheel: "旋轉",
  clearBets: "清除",
  undo: "復原",
  onTable: "桌上押注",
  tableWin: "你贏了",
  tableLose: "這次運氣不佳",
  placeBetFirst: "請先下注",
  lastNumbers: "最近開出",
  red: "紅", black: "黑", odd: "單", even: "雙",
  rules: "規則",
  login: "登入",
  register: "註冊",
  username: "帳號",
  password: "密碼",
  spin: "旋轉",
  bet: "押注",
  balance: "餘額",
  logout: "登出",
  leaderboard: "傳奇殿堂",
  loading: "好運召喚中...",
  streak: "連勝",
  topUp: "免費金幣",
  autoSpin: "自動",
  totalWins: "總贏得",
  maxWin: "最大獎",
  gamesPlayed: "遊戲局數",
  deposit: "免費金幣",
  about: "關於",
  terms: "條款",
  support: "客服",
  beginQuest: "免費暢玩",
  subtitle: "888 神龍發財",
  description: "一款免費的越南風格老虎機。轉動轉輪，連成",
  descriptionDragon: "神龍",
  descriptionEnd: "，再試試魚蝦蟹和輪盤，全部共用一個金幣餘額。只使用遊戲金幣——不用真錢儲值，也無法提領真錢。",
  maxWinStat: "最高派彩",
  freeSpins: "免費旋轉",
  dailyCoins: "每日金幣",
  feature1: "10 條連線",
  feature1Desc: "5 個轉輪、3 列：從左起 3、4 或 5 個相連即中獎。每次中獎至少拿回你的押注",
  feature2: "百搭與紅包",
  feature2Desc: "🔮 龍珠百搭可補齊連線。🧧 3 個以上紅包在任何位置都派彩，而且由你選擇免費旋轉方式",
  feature3: "神龍連轉與神龍彩金",
  feature3Desc: "任意位置 3 個 🔮 喚醒神龍：龍珠保留，其餘以 ×2 到 ×12 重轉。中間列 🔮🔮🔮 引爆共享彩金",
  achievements: "成就",
  topPlayers: "頂尖玩家",
  won: "贏得",
  noPlayersYet: "還沒有玩家",
  noWinsYet: "還沒有大獎——搶當第一個！",
  games: "局數",
  wins: "贏局",
  profile: "個人檔案",
  insufficientBalance: "金幣不足",
  insufficientBalanceDesc: "降低押注，或領取每日免費金幣。",
  niceWin: "漂亮！",
  bigWin: "大獎！",
  hugeWin: "超級大獎！",
  megaWin: "神龍發財！",
  youWon: "你贏得",
  smallWin: "小獎",
  scatterWin: "幸運紅包！",
  freeSpinsMode: "免費旋轉",
  wild: "百搭",
  scatter: "分散",
  anywhere: "任意位置",
  paytableWild: "🔮 龍珠是百搭：可代替連線上的任何符號，連續的龍珠本身也會派彩（上方 🔮 那一列）。",
  paytableScatter: "🧧 紅包在任何位置都派彩，不需連線，還能贏得免費旋轉。你可以選擇領取方式（選紅包）：較多次旋轉，或較少次但每次獎金加倍。每種選擇的平均價值都相同：",
  noWin: "這次沒中",
  freeSpinsLeft: "次免費旋轉",
  freeSpinsWon: "次免費旋轉到手！",
  oracle: "龍神求籤",
  oracleBlessed: "求一支籤：籤運加持你的下一次旋轉（×1.5 到 ×5）",
  oracleCooldown: "龍神正在休息。再次開放時間：",
  blessedBadge: "下次旋轉已加持",
  paytable: "賠率表",
  paytableIntro: "在 10 條連線中的任一條上，從最左邊轉輪起連續 3、4 或 5 個相同符號，即派彩下方倍數乘以你的押注。所有連線獎金累加。",
  paytableFree: "免費旋轉以贏得時的押注進行。免費旋轉中再出現紅包，可用相同倍數增加旋轉次數。",
  rtpNote: "返還率：以最佳「保留轉輪」選擇遊玩為 95.9%（從不保留則為 87.7%；以 4,000 萬次旋轉測得），另加 1% 注入彩金。搖碟比倍 (Xóc Đĩa) 完全按公平賠率派彩，因此不影響此數字。每個符號都由加密等級的亂數產生器獨立抽出。",
  repeater: "神龍連轉",
  repeaterGo: "神龍連轉",
  paytableRepeater: "🐉 神龍連轉：任意位置 2 個 🔮 喚醒神龍，獲得兩次免費重轉；3 個以上則開啟完整倍數階梯。龍珠保留、中獎符號鎖定，其餘免費重轉。每條新連線，或變長的連線，都以下一個倍數派彩，只要你持續贏就會繼續：",
  jackpotName: "神龍彩金",
  jackpotWin: "彩金爆發！",
  paytableJackpot: "🏺 神龍彩金：每次押注的 1% 注入共享彩池。轉輪 1-3 中間列出現三個 🔮（正常旋轉或任何連轉皆可）即贏得彩金：你的份額隨押注增加：1K 贏得彩池的 0.1%，100K 贏得 10%，1M 贏得整個彩池。彩池永不低於 1 億，所以每次押注至少贏得 100 倍。",
  jackpotLast: "上次得主",
  jackpotYourBet: "你的押注",
  error: "錯誤",
  copyright: "© VnSlot 888 · 免費娛樂 · 18+",
  live: "大獎快訊",
  firstName: "名字",
  lastName: "姓氏",
  saveChanges: "儲存變更",
  memberSince: "加入時間",
  editProfile: "編輯個人檔案",
  profileUpdated: "個人檔案已更新",
  changePassword: "變更密碼",
  currentPassword: "目前密碼",
  newPassword: "新密碼",
  passwordChanged: "密碼已變更",
  playMoneyNote: "金幣僅供娛樂，無法用真錢購買，也無法兌換成現金、獎品或任何有價物品。",
  sound: "音效",
  max: "最佳",
  onFire: "手氣正旺！",
  unstoppable: "勢不可擋！",
  dragonMode: "神龍模式！",
  rank: "名次",
  legendsTagline: "神龍傳奇",
  emptyLeaderboard: "競技場一片寂靜。搶先登上王座吧！",
};

const translations: Record<Language, Translations> = { en, vi, zh };

const LanguageContext = createContext<{
  lang: Language;
  setLang: (lang: Language) => void;
  /** Moves to the next language in the list */
  toggleLang: () => void;
  t: Translations;
  /** Picks the Vietnamese, English or Chinese version */
  tr: <T,>(vi: T, en: T, zh: T) => T;
  /** Picks this language's version of a translated piece of text (English if it has no Chinese) */
  loc: (text: LocalText) => string;
  /** The locale for dates and times */
  locale: string;
  /** A message from the server, in this language when we have it translated */
  srv: (message: string) => string;
} | null>(null);

// The language being shown, for formatting helpers that live outside components
let currentLang: Language = "vi";
/** A coin amount, written the way this language writes numbers (Chinese uses commas: 5,000) */
export const fmtCoins = (n: number) => n.toLocaleString(currentLang === "zh" ? "zh-TW" : "vi-VN");

const isLanguage = (v: unknown): v is Language => LANGUAGES.some((l) => l.id === v);

function initialLang(): Language {
  try {
    const saved = localStorage.getItem("lang");
    if (isLanguage(saved)) return saved;
  } catch {}
  return "vi";
}

const htmlLang = (lang: Language) => LANGUAGES.find((l) => l.id === lang)!.html;

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(initialLang);
  currentLang = lang;

  useEffect(() => { document.documentElement.lang = htmlLang(lang); }, [lang]);

  const setLang = (next: Language) => {
    try { localStorage.setItem("lang", next); } catch {}
    setLangState(next);
  };
  const toggleLang = () => {
    const i = LANGUAGES.findIndex((l) => l.id === lang);
    setLang(LANGUAGES[(i + 1) % LANGUAGES.length].id);
  };
  const tr = <T,>(vi: T, en: T, zhText: T): T => (lang === "vi" ? vi : lang === "zh" ? zhText : en);
  const loc = (text: LocalText) => (lang === "vi" ? text.vi : lang === "zh" ? text.zh ?? text.en : text.en);
  const locale = LANGUAGES.find((l) => l.id === lang)!.locale;
  const srv = (message: string) => (lang === "en" ? message : SERVER_MESSAGES[message]?.[lang] ?? message);

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t: translations[lang], tr, loc, locale, srv }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLang must be used within LanguageProvider");
  return context;
}
