import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "vi";

const en = {
  installTitle: "Get the VnSlot 888 app",
  installDesc: "Free. Opens full-screen from your home screen, like any app.",
  installBannerSub: "Play from your home screen, full-screen",
  installShort: "Install app",
  installNow: "Install now",
  installDone: "Installed. Open VnSlot 888 from your home screen.",
  installIos1: "In Safari, tap the Share button",
  installIos2: "Scroll down and tap",
  installIosAdd: "Add to Home Screen",
  installIos3: "Tap",
  installIosConfirm: "Add",
  installAndroid1: "In Chrome, tap the menu",
  installAndroid2: "Tap “Install app” or “Add to Home screen”",
  notNow: "Not now",
  privacy: "Privacy",
  deleteAccount: "Delete account",
  deleteAccountDesc: "Permanently deletes your account, coins, statistics and achievements. This can't be undone.",
  deleteConfirm: "I understand my account and coins will be gone for good",
  accountDeleted: "Your account has been deleted",
  gameSlot: "Slot",
  gameBauCua: "Bầu Cua",
  gameRoulette: "Roulette",
  gameBlackjack: "Blackjack",
  gamePool: "Pool",
  bcTitle: "Bầu Cua Tôm Cá",
  bcSubtitle: "The Tết dice game",
  bcNames: { bau: "Gourd", cua: "Crab", tom: "Shrimp", ca: "Fish", ga: "Rooster", nai: "Deer" },
  bcRules: "Bet on any of the six pictures, then roll three dice. A picture on one die pays 1 to 1, on two dice 2 to 1, on all three 3 to 1. Return to player: 92.13%, exactly as the traditional game.",
  rlTitle: "Roulette",
  rlSubtitle: "European single zero",
  rlRules: "Bet on a number (pays 35 to 1), a dozen or column (2 to 1), or red/black, odd/even, 1-18/19-36 (1 to 1). Zero loses every outside bet. Return to player: 97.30%.",
  pickChip: "Pick a chip, then tap where to bet",
  roll: "ROLL",
  spinWheel: "SPIN",
  clearBets: "Clear",
  undo: "Undo",
  onTable: "On the table",
  tableWin: "You won",
  tableLose: "No luck this time",
  placeBetFirst: "Place a bet first",
  lastNumbers: "Last numbers",
  red: "Red", black: "Black", odd: "Odd", even: "Even",
  rules: "Rules",
  login: "Enter Realm",
  register: "Join Dynasty",
  username: "Username",
  password: "Password",
  spin: "SPIN",
  bet: "Bet",
  balance: "Treasury",
  logout: "Log out",
  leaderboard: "Hall of Legends",
  loading: "Summoning luck...",
  streak: "Win Streak",
  topUp: "Free Coins",
  autoSpin: "Auto",
  totalWins: "Total Wins",
  maxWin: "Biggest Win",
  gamesPlayed: "Games Played",
  deposit: "Free Coins",
  about: "About",
  terms: "Terms",
  support: "Support",
  beginQuest: "Play Free",
  subtitle: "888 Dragon Fortune",
  description: "A free-to-play Vietnamese-style slot. Spin the reels, line up the",
  descriptionDragon: "Dragon",
  descriptionEnd: ", then try Bầu Cua Tôm Cá and roulette, all on one coin balance. Play money only — no real money in, no real money out.",
  maxWinStat: "TOP PAYOUT",
  freeSpins: "FREE SPINS",
  dailyCoins: "DAILY COINS",
  feature1: "10 PAYLINES",
  feature1Desc: "5 reels, 3 rows: 3, 4 or 5 in a row from the left. Every win pays at least your bet back",
  feature2: "WILDS & LÌ XÌ",
  feature2Desc: "🔮 Dragon Pearl wilds complete lines. 🧧 3+ red envelopes pay anywhere and you choose your free spins",
  feature3: "RỒNG LẶP & HŨ RỒNG",
  feature3Desc: "3 🔮 anywhere wake the dragon: pearls stick and the rest re-spins at ×2 to ×12. Middle-row 🔮🔮🔮 bursts the shared jackpot",
  achievements: "Achievements",
  topPlayers: "Top Players",
  won: "won",
  noPlayersYet: "No players yet",
  noWinsYet: "No big wins yet — be the first!",
  games: "Games",
  wins: "Wins",
  profile: "Profile",
  insufficientBalance: "Not enough coins",
  insufficientBalanceDesc: "Lower your bet or grab your free daily coins.",
  niceWin: "NICE WIN!",
  bigWin: "BIG WIN!",
  hugeWin: "MEGA WIN!",
  megaWin: "DRAGON FORTUNE!",
  youWon: "You won",
  smallWin: "Small win",
  scatterWin: "LUCKY ENVELOPES!",
  freeSpinsMode: "FREE SPINS",
  wild: "WILD",
  scatter: "SCATTER",
  anywhere: "anywhere",
  paytableWild: "🔮 Dragon Pearl is WILD: it stands in for any symbol on a line, and a run of pearls pays by itself (the 🔮 row above).",
  paytableScatter: "🧧 Red envelopes pay anywhere, no line needed, and win free spins. You choose how to take them (Chọn Lì Xì): more spins, or fewer spins with every win multiplied. Every choice is worth the same on average:",
  noWin: "No win this time",
  freeSpinsLeft: "free spins",
  freeSpinsWon: "free spins won!",
  oracle: "Oracle",
  oracleBlessed: "Draw a fortune stick: its grade blesses your next spin (×1.5 to ×5)",
  oracleCooldown: "The Oracle is resting. Back at",
  blessedBadge: "BLESSED NEXT SPIN",
  paytable: "Paytable",
  paytableIntro: "3, 4 or 5 matching symbols in a row from the leftmost reel, on any of the 10 lines, pay the multiple below times your bet. All lines add up.",
  paytableFree: "Free spins are played at the bet that won them. More envelopes during free spins add spins at the same multiplier.",
  rtpNote: "Return to player: 96.6% from the game with the best HOLD choices (87.7% if you never hold; measured over 40 million spins) plus the 1% that feeds the jackpot. The Xóc Đĩa double-up pays exactly fair odds, so it never changes that. Every symbol is drawn independently by a cryptographic RNG.",
  repeater: "RỒNG LẶP",
  repeaterGo: "RỒNG LẶP",
  paytableRepeater: "🐉 Rồng Lặp: 3 or more 🔮 anywhere wake the dragon. The pearls stick, winning symbols lock and everything else re-spins free. Each new line, or a line that grows longer, pays with the next multiplier, and it keeps going while you keep winning:",
  jackpotName: "HŨ RỒNG",
  jackpotWin: "NỔ HŨ!",
  paytableJackpot: "🏺 Hũ Rồng jackpot: 1% of every bet goes into a shared pot. Three 🔮 on the middle row of reels 1-3 (on the spin or any repeat) win it: your share grows with your bet: 1K wins 0.1% of the pot, 100K wins 10%, 1M wins the whole pot. The pot never drops below 100M, so every bet wins at least 100× itself.",
  jackpotLast: "Last won by",
  jackpotYourBet: "Your bet",
  error: "Error",
  copyright: "© VnSlot 888 · Free-to-play entertainment · 18+",
  live: "BIG WINS",
  firstName: "First Name",
  lastName: "Last Name",
  saveChanges: "Save Changes",
  memberSince: "Member Since",
  editProfile: "Edit Profile",
  profileUpdated: "Profile updated",
  changePassword: "Change Password",
  currentPassword: "Current password",
  newPassword: "New password",
  passwordChanged: "Password changed",
  playMoneyNote: "Coins are play money. They can't be bought for cash or exchanged for money or prizes.",
  sound: "Sound",
  max: "Best",
  onFire: "On Fire!",
  unstoppable: "Unstoppable!",
  dragonMode: "Dragon Mode!",
  rank: "Rank",
  legendsTagline: "Legends of the Dragon",
  emptyLeaderboard: "The arena is silent. Be the first to claim your throne!",
};

export type Translations = typeof en;

const vi: Translations = {
  installTitle: "Tải ứng dụng VnSlot 888",
  installDesc: "Miễn phí. Mở toàn màn hình từ màn hình chính, như mọi ứng dụng.",
  installBannerSub: "Chơi ngay từ màn hình chính, toàn màn hình",
  installShort: "Tải ứng dụng",
  installNow: "Cài đặt ngay",
  installDone: "Đã cài đặt. Mở VnSlot 888 từ màn hình chính.",
  installIos1: "Trong Safari, chạm nút Chia sẻ",
  installIos2: "Kéo xuống và chạm",
  installIosAdd: "Thêm vào MH chính",
  installIos3: "Chạm",
  installIosConfirm: "Thêm",
  installAndroid1: "Trong Chrome, chạm vào menu",
  installAndroid2: "Chạm “Cài đặt ứng dụng” hoặc “Thêm vào màn hình chính”",
  notNow: "Để sau",
  privacy: "Quyền riêng tư",
  deleteAccount: "Xoá tài khoản",
  deleteAccountDesc: "Xoá vĩnh viễn tài khoản, xu, thống kê và thành tích của bạn. Không thể hoàn tác.",
  deleteConfirm: "Tôi hiểu tài khoản và xu sẽ bị xoá vĩnh viễn",
  accountDeleted: "Tài khoản của bạn đã được xoá",
  gameSlot: "Slot",
  gameBauCua: "Bầu Cua",
  gameRoulette: "Roulette",
  gameBlackjack: "Xì Dách",
  gamePool: "Bi-a",
  bcTitle: "Bầu Cua Tôm Cá",
  bcSubtitle: "Trò chơi ngày Tết",
  bcNames: { bau: "Bầu", cua: "Cua", tom: "Tôm", ca: "Cá", ga: "Gà", nai: "Nai" },
  bcRules: "Đặt cược vào một trong sáu linh vật rồi lắc ba xúc xắc. Ra một mặt trả 1 ăn 1, hai mặt 1 ăn 2, ba mặt 1 ăn 3. Tỷ lệ hoàn trả: 92,13%, đúng như trò chơi truyền thống.",
  rlTitle: "Roulette",
  rlSubtitle: "Châu Âu, một số 0",
  rlRules: "Cược một số (1 ăn 35), một tá hoặc một cột (1 ăn 2), hoặc đỏ/đen, lẻ/chẵn, 1-18/19-36 (1 ăn 1). Số 0 thua mọi cược ngoài. Tỷ lệ hoàn trả: 97,30%.",
  pickChip: "Chọn phỉnh rồi chạm vào ô để cược",
  roll: "LẮC",
  spinWheel: "QUAY",
  clearBets: "Xoá",
  undo: "Hoàn tác",
  onTable: "Tiền cược",
  tableWin: "Bạn thắng",
  tableLose: "Chưa may mắn",
  placeBetFirst: "Hãy đặt cược trước",
  lastNumbers: "Kết quả gần đây",
  red: "Đỏ", black: "Đen", odd: "Lẻ", even: "Chẵn",
  rules: "Luật chơi",
  login: "Vào Cung",
  register: "Gia Nhập",
  username: "Tên đăng nhập",
  password: "Mật khẩu",
  spin: "QUAY",
  bet: "Mức Cược",
  balance: "Ngân Khố",
  logout: "Đăng xuất",
  leaderboard: "Bảng Phong Thần",
  loading: "Đang triệu hồi...",
  streak: "Chuỗi Thắng",
  topUp: "Xu Miễn Phí",
  autoSpin: "Tự động",
  totalWins: "Tổng Thắng",
  maxWin: "Thắng Lớn Nhất",
  gamesPlayed: "Lượt Chơi",
  deposit: "Xu Miễn Phí",
  about: "Giới Thiệu",
  terms: "Điều Khoản",
  support: "Hỗ Trợ",
  beginQuest: "Chơi Miễn Phí",
  subtitle: "888 Long Phát Tài",
  description: "Trò chơi slot phong cách Việt, hoàn toàn miễn phí. Quay, xếp hàng",
  descriptionDragon: "Rồng",
  descriptionEnd: ", rồi thử Bầu Cua Tôm Cá và Roulette, chung một ví xu. Chỉ dùng xu ảo — không nạp tiền thật, không rút tiền thật.",
  maxWinStat: "THƯỞNG CAO NHẤT",
  freeSpins: "LƯỢT QUAY MIỄN PHÍ",
  dailyCoins: "XU MỖI NGÀY",
  feature1: "10 HÀNG THƯỞNG",
  feature1Desc: "5 cuộn, 3 hàng: 3, 4 hoặc 5 biểu tượng liền nhau từ trái. Mọi lần thắng đều ít nhất hoàn lại tiền cược",
  feature2: "WILD & LÌ XÌ",
  feature2Desc: "🔮 Ngọc Rồng thay thế mọi biểu tượng. 🧧 3 lì xì trở lên trả thưởng ở bất kỳ ô nào và bạn tự chọn lượt quay miễn phí",
  feature3: "RỒNG LẶP & HŨ RỒNG",
  feature3Desc: "3 🔮 ở bất kỳ đâu đánh thức Rồng: ngọc được giữ lại, phần còn lại quay tiếp với hệ số ×2 đến ×12. 🔮🔮🔮 hàng giữa làm nổ hũ chung",
  achievements: "Thành Tựu",
  topPlayers: "Người Chơi Hàng Đầu",
  won: "thắng",
  noPlayersYet: "Chưa có người chơi",
  noWinsYet: "Chưa có thắng lớn — hãy là người đầu tiên!",
  games: "Ván",
  wins: "Thắng",
  profile: "Hồ Sơ",
  insufficientBalance: "Không đủ xu",
  insufficientBalanceDesc: "Giảm mức cược hoặc nhận xu miễn phí hằng ngày.",
  niceWin: "THẮNG ĐẸP!",
  bigWin: "THẮNG LỚN!",
  hugeWin: "THẮNG CỰC LỚN!",
  megaWin: "LONG PHÁT TÀI!",
  youWon: "Bạn thắng",
  smallWin: "Thắng nhỏ",
  scatterWin: "LÌ XÌ MAY MẮN!",
  freeSpinsMode: "QUAY MIỄN PHÍ",
  wild: "WILD",
  scatter: "SCATTER",
  anywhere: "bất kỳ đâu",
  paytableWild: "🔮 Ngọc Rồng là WILD: thay thế mọi biểu tượng trên hàng thưởng, và một chuỗi ngọc cũng tự trả thưởng (dòng 🔮 ở trên).",
  paytableScatter: "🧧 Lì xì trả thưởng ở bất kỳ ô nào, không cần xếp hàng, và tặng lượt quay miễn phí. Bạn tự chọn cách nhận (Chọn Lì Xì): nhiều lượt, hoặc ít lượt hơn nhưng mọi khoản thắng được nhân lên. Mọi lựa chọn có giá trị trung bình như nhau:",
  noWin: "Chưa trúng lần này",
  freeSpinsLeft: "lượt miễn phí",
  freeSpinsWon: "lượt quay miễn phí!",
  oracle: "Thần Rồng",
  oracleBlessed: "Xin một quẻ xăm: quẻ càng tốt, lượt quay tới càng được nhân nhiều (×1,5 đến ×5)",
  oracleCooldown: "Thần Rồng đang nghỉ. Quay lại lúc",
  blessedBadge: "ĐƯỢC BAN PHƯỚC",
  paytable: "Bảng Thưởng",
  paytableIntro: "3, 4 hoặc 5 biểu tượng giống nhau liền nhau từ cuộn đầu tiên bên trái, trên bất kỳ hàng nào trong 10 hàng, trả bội số dưới đây nhân với mức cược. Các hàng được cộng dồn.",
  paytableFree: "Lượt quay miễn phí dùng mức cược đã thắng chúng. Lì xì trong lượt miễn phí cho thêm lượt với cùng hệ số nhân.",
  rtpNote: "Tỷ lệ hoàn trả: 96,6% từ trò chơi khi giữ cuộn đúng cách (87,7% nếu không bao giờ giữ; đo trên 40 triệu lượt quay) cộng 1% góp vào hũ. Xóc Đĩa nhân đôi trả đúng tỷ lệ công bằng nên không làm thay đổi con số này. Mỗi biểu tượng được chọn độc lập bằng bộ sinh số ngẫu nhiên mật mã.",
  repeater: "RỒNG LẶP",
  repeaterGo: "RỒNG LẶP",
  paytableRepeater: "🐉 Rồng Lặp: 3 🔮 trở lên ở bất kỳ đâu sẽ đánh thức Rồng. Ngọc Rồng được giữ lại, biểu tượng thắng được khóa và phần còn lại quay miễn phí. Mỗi hàng thắng mới, hoặc hàng dài thêm, được nhân hệ số tiếp theo, và tiếp tục chừng nào bạn còn thắng:",
  jackpotName: "HŨ RỒNG",
  jackpotWin: "NỔ HŨ!",
  paytableJackpot: "🏺 Hũ Rồng: 1% mỗi lượt cược được góp vào hũ chung. Ba 🔮 ở hàng giữa của cuộn 1-3 (lượt quay hoặc lượt lặp) sẽ nổ hũ: phần thưởng tăng theo mức cược: 1K nhận 0,1% hũ, 100K nhận 10%, 1M nhận toàn bộ hũ. Hũ không bao giờ dưới 100 triệu, nên mọi mức cược đều thắng ít nhất 100 lần.",
  jackpotLast: "Lần nổ gần nhất",
  jackpotYourBet: "Cược",
  error: "Lỗi",
  copyright: "© VnSlot 888 · Giải trí miễn phí · 18+",
  live: "THẮNG LỚN",
  firstName: "Tên",
  lastName: "Họ",
  saveChanges: "Lưu Thay Đổi",
  memberSince: "Thành Viên Từ",
  editProfile: "Chỉnh Sửa Hồ Sơ",
  profileUpdated: "Đã cập nhật hồ sơ",
  changePassword: "Đổi Mật Khẩu",
  currentPassword: "Mật khẩu hiện tại",
  newPassword: "Mật khẩu mới",
  passwordChanged: "Đã đổi mật khẩu",
  playMoneyNote: "Xu chỉ dùng để chơi. Không thể mua bằng tiền thật hay đổi ra tiền hoặc giải thưởng.",
  sound: "Âm thanh",
  max: "Cao nhất",
  onFire: "Đang Bốc Lửa!",
  unstoppable: "Không Thể Cản!",
  dragonMode: "Chế Độ Rồng!",
  rank: "Hạng",
  legendsTagline: "Huyền Thoại Của Rồng",
  emptyLeaderboard: "Đấu trường còn trống. Hãy là người đầu tiên lên ngôi!",
};

const translations: Record<Language, Translations> = { en, vi };

const LanguageContext = createContext<{
  lang: Language;
  toggleLang: () => void;
  t: Translations;
} | null>(null);

function initialLang(): Language {
  try {
    const saved = localStorage.getItem("lang");
    if (saved === "en" || saved === "vi") return saved;
  } catch {}
  return "vi";
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Language>(initialLang);

  const toggleLang = () => setLang((prev) => {
    const next = prev === "en" ? "vi" : "en";
    try { localStorage.setItem("lang", next); } catch {}
    document.documentElement.lang = next;
    return next;
  });

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t: translations[lang] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLang must be used within LanguageProvider");
  return context;
}
